/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type Duration = {
  hours?: number;
  minutes?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type PersonReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "person";
};

export type Club = {
  _id: string;
  _type: "club";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  managers?: Array<{
    person?: PersonReference;
    role?: string;
    _key: string;
  }>;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type InfoPage = {
  _id: string;
  _type: "infoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  menuPlacement?: Array<string>;
  order?: number;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
};

export type PaymentInfo = {
  _type: "paymentInfo";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  vippsNumber?: string;
  url?: string;
};

export type Person = {
  _id: string;
  _type: "person";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  email?: string;
  phone?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type ClubReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "club";
};

export type LocationReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "location";
};

export type SessionSeries = {
  _id: string;
  _type: "sessionSeries";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sport?:
    | "fotball"
    | "klatring"
    | "handball"
    | "turn"
    | "innebandy"
    | "allidrett";
  sessions?: Array<
    {
      _key: string;
    } & Session
  >;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  organizers?: ArrayOf<PersonReference | ClubReference>;
  location?: LocationReference;
  paymentInfo?: PaymentInfo;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  slug?: Slug;
};

export type Session = {
  _type: "session";
  startsAt?: string;
  duration?: Duration;
  cancelled?: boolean;
  note?: string;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  sport?:
    | "fotball"
    | "klatring"
    | "handball"
    | "turn"
    | "innebandy"
    | "allidrett";
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  startsAt?: string;
  endsAt?: string;
  location?: LocationReference;
  organizers?: ArrayOf<PersonReference | ClubReference>;
  paymentInfo?: PaymentInfo;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  parent?: LocationReference;
  address?: string;
  zip?: string;
  city?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  heroTitle?: string;
  heroText?: string;
  footerText?: string;
  contactEmail?: string;
  intro?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Duration
  | SanityImageAssetReference
  | PersonReference
  | Club
  | Slug
  | SanityImageCrop
  | SanityImageHotspot
  | InfoPage
  | PaymentInfo
  | Person
  | ClubReference
  | LocationReference
  | SessionSeries
  | Session
  | Event
  | Location
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/app/(frontend)/aktiviteter/[slug]/page.tsx
// Variable: aktivitetQuery
// Query: *[_type in ["sessionSeries", "event"] && (slug.current == $slug || _id == $slug)][0]{  ...,  location->,  organizers[]->,}
export type AktivitetQueryResult =
  | {
      _id: string;
      _type: "event";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      sport?:
        | "allidrett"
        | "fotball"
        | "handball"
        | "innebandy"
        | "klatring"
        | "turn";
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      startsAt?: string;
      endsAt?: string;
      location: {
        _id: string;
        _type: "location";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
        parent?: LocationReference;
        address?: string;
        zip?: string;
        city?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h2" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        slug?: Slug;
      } | null;
      organizers: Array<
        | {
            _id: string;
            _type: "club";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            name?: string;
            images?: Array<{
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }>;
            managers?: Array<{
              person?: PersonReference;
              role?: string;
              _key: string;
            }>;
            body?: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }>;
            slug?: Slug;
          }
        | {
            _id: string;
            _type: "person";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            name?: string;
            email?: string;
            phone?: string;
            image?: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
            };
          }
      > | null;
      paymentInfo?: PaymentInfo;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
    }
  | {
      _id: string;
      _type: "sessionSeries";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      title?: string;
      sport?:
        | "allidrett"
        | "fotball"
        | "handball"
        | "innebandy"
        | "klatring"
        | "turn";
      sessions?: Array<
        {
          _key: string;
        } & Session
      >;
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      organizers: Array<
        | {
            _id: string;
            _type: "club";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            name?: string;
            images?: Array<{
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
              _key: string;
            }>;
            managers?: Array<{
              person?: PersonReference;
              role?: string;
              _key: string;
            }>;
            body?: Array<{
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "h2" | "normal";
              listItem?: "bullet" | "number";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }>;
            slug?: Slug;
          }
        | {
            _id: string;
            _type: "person";
            _createdAt: string;
            _updatedAt: string;
            _rev: string;
            name?: string;
            email?: string;
            phone?: string;
            image?: {
              asset?: SanityImageAssetReference;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              _type: "image";
            };
          }
      > | null;
      location: {
        _id: string;
        _type: "location";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        name?: string;
        images?: Array<{
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }>;
        parent?: LocationReference;
        address?: string;
        zip?: string;
        city?: string;
        body?: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "h2" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
        slug?: Slug;
      } | null;
      paymentInfo?: PaymentInfo;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      slug?: Slug;
    }
  | null;

// Source: src/app/(frontend)/components/RecurringEvents.tsx
// Variable: reoccurringEventsQuery
// Query: {  "sessionSeries": *[    _type == "sessionSeries"  ]  {    _id,    title,    slug,    sport,    "sessions": sessions[] {      "startsAt": dateTime(startsAt),      "endsAt": dateTime(startsAt) + duration.hours * 60 * 60 + duration.minutes * 60,    } [defined(startsAt) && dateTime(endsAt) > dateTime(now())] | order(startsAt asc) [0...1],  } | order(title asc),}
export type ReoccurringEventsQueryResult = {
  sessionSeries: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    sport:
      | "allidrett"
      | "fotball"
      | "handball"
      | "innebandy"
      | "klatring"
      | "turn"
      | null;
    sessions: Array<{
      startsAt: string | null;
      endsAt: string | null;
    }> | null;
  }>;
};

// Source: src/app/(frontend)/components/calendar.tsx
// Variable: activitiesQuery
// Query: {  "events": *[    _type == "event" &&    endsAt > now() &&    (!defined($seriesId) || _id == $seriesId) &&    (!defined($locationId) || location._ref == $locationId) &&    (!defined($clubId) || references($clubId))  ] | order(startsAt asc) {    _id,    _type,    title,    startsAt,    endsAt,    location->{ _id, name },  },  "sessionSeries": *[    _type == "sessionSeries" &&    (!defined($seriesId) || _id == $seriesId) &&    (!defined($locationId) || location._ref == $locationId) &&    (!defined($clubId) || references($clubId))  ] {    _id,    title,    slug,    location->{ _id, name },    "sessions": sessions[] {      _key,      cancelled,      note,      "startsAt": dateTime(startsAt),      "endsAt": dateTime(startsAt) + duration.hours * 60 * 60 + duration.minutes * 60,    } [defined(startsAt) && dateTime(endsAt) > dateTime(now())] | order(startsAt asc) [0...$sessionLimit],  },}
export type ActivitiesQueryResult = {
  events: Array<{
    _id: string;
    _type: "event";
    title: string | null;
    startsAt: string | null;
    endsAt: string | null;
    location: {
      _id: string;
      name: string | null;
    } | null;
  }>;
  sessionSeries: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    location: {
      _id: string;
      name: string | null;
    } | null;
    sessions: Array<{
      _key: string;
      cancelled: boolean | null;
      note: string | null;
      startsAt: string | null;
      endsAt: string | null;
    }> | null;
  }>;
};

// Source: src/app/(frontend)/info/[slug]/page.tsx
// Variable: infoPageQuery
// Query: *[_type == "infoPage" && slug.current == $slug][0]
export type InfoPageQueryResult = {
  _id: string;
  _type: "infoPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  menuPlacement?: Array<string>;
  order?: number;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
} | null;

// Source: src/app/(frontend)/klubber/[slug]/page.tsx
// Variable: clubPageQuery
// Query: *[_type == "club" && slug.current == $slug][0] {    ...,    managers[] {      ...,      person->    }  }
export type ClubPageQueryResult = {
  _id: string;
  _type: "club";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  managers: Array<{
    person: {
      _id: string;
      _type: "person";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      email?: string;
      phone?: string;
      image?: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
      };
    } | null;
    role?: string;
    _key: string;
  }> | null;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
} | null;

// Source: src/app/(frontend)/layout.tsx
// Variable: faviconQuery
// Query: *[_type == "siteSettings"][0]{ logo }
export type FaviconQueryResult = {
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
} | null;

// Source: src/app/(frontend)/layout/Footer.tsx
// Variable: footerQuery
// Query: {  "siteSettings": *[_type == "siteSettings"][0]{ footerText, contactEmail },  "infoPages": *[_type == "infoPage"] | order(order asc, title asc) {    title,    slug,    menuPlacement,  }}
export type FooterQueryResult = {
  siteSettings: {
    footerText: string | null;
    contactEmail: string | null;
  } | null;
  infoPages: Array<{
    title: string | null;
    slug: Slug | null;
    menuPlacement: Array<string> | null;
  }>;
};

// Source: src/app/(frontend)/layout/Header.tsx
// Variable: headerQuery
// Query: {  "siteSettings": *[_type == "siteSettings"][0]{ logo },  "infoPages": *[_type == "infoPage"] | order(order asc, title asc) {    title,    slug,    menuPlacement,  },  "clubs": *[_type == "club"] | order(name asc) { name, slug }}
export type HeaderQueryResult = {
  siteSettings: {
    logo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
  infoPages: Array<{
    title: string | null;
    slug: Slug | null;
    menuPlacement: Array<string> | null;
  }>;
  clubs: Array<{
    name: string | null;
    slug: Slug | null;
  }>;
};

// Source: src/app/(frontend)/lokaler/[slug]/page.tsx
// Variable: lokasjonQuery
// Query: *[_type == "location" && slug.current == $slug][0]{  ...,}
export type LokasjonQueryResult = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  parent?: LocationReference;
  address?: string;
  zip?: string;
  city?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
} | null;

// Source: src/app/(frontend)/lokaler/page.tsx
// Variable: locationsQuery
// Query: *[_type == "location"] | order(name asc)
export type LocationsQueryResult = Array<{
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  parent?: LocationReference;
  address?: string;
  zip?: string;
  city?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  slug?: Slug;
}>;

// Source: src/app/(frontend)/page.tsx
// Variable: frontPageQuery
// Query: {  "settings": *[_type == "siteSettings"][0]{ heroTitle, heroText },  "intro": *[_type == "siteSettings"][0].intro,  "events": *[_type == "event" && endsAt > now()] | order(startsAt asc) {    ...,    location->,  }}
export type FrontPageQueryResult = {
  settings: {
    heroTitle: string | null;
    heroText: string | null;
  } | null;
  intro: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "h2" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  events: Array<{
    _id: string;
    _type: "event";
    _createdAt: string;
    _updatedAt: string;
    _rev: string;
    title?: string;
    sport?:
      | "allidrett"
      | "fotball"
      | "handball"
      | "innebandy"
      | "klatring"
      | "turn";
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "h2" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    startsAt?: string;
    endsAt?: string;
    location: {
      _id: string;
      _type: "location";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      parent?: LocationReference;
      address?: string;
      zip?: string;
      city?: string;
      body?: Array<{
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "h2" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }>;
      slug?: Slug;
    } | null;
    organizers?: ArrayOf<ClubReference | PersonReference>;
    paymentInfo?: PaymentInfo;
    images?: Array<{
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }>;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type in ["sessionSeries", "event"] && (slug.current == $slug || _id == $slug)][0]{\n  ...,\n  location->,\n  organizers[]->,\n}': AktivitetQueryResult;
    '{\n  "sessionSeries": *[\n    _type == "sessionSeries"\n  ]\n  {\n    _id,\n    title,\n    slug,\n    sport,\n    "sessions": sessions[] {\n      "startsAt": dateTime(startsAt),\n      "endsAt": dateTime(startsAt) + duration.hours * 60 * 60 + duration.minutes * 60,\n    } [defined(startsAt) && dateTime(endsAt) > dateTime(now())] | order(startsAt asc) [0...1],\n  } | order(title asc),\n}': ReoccurringEventsQueryResult;
    '{\n  "events": *[\n    _type == "event" &&\n    endsAt > now() &&\n    (!defined($seriesId) || _id == $seriesId) &&\n    (!defined($locationId) || location._ref == $locationId) &&\n    (!defined($clubId) || references($clubId))\n  ] | order(startsAt asc) {\n    _id,\n    _type,\n    title,\n    startsAt,\n    endsAt,\n    location->{ _id, name },\n  },\n  "sessionSeries": *[\n    _type == "sessionSeries" &&\n    (!defined($seriesId) || _id == $seriesId) &&\n    (!defined($locationId) || location._ref == $locationId) &&\n    (!defined($clubId) || references($clubId))\n  ] {\n    _id,\n    title,\n    slug,\n    location->{ _id, name },\n    "sessions": sessions[] {\n      _key,\n      cancelled,\n      note,\n      "startsAt": dateTime(startsAt),\n      "endsAt": dateTime(startsAt) + duration.hours * 60 * 60 + duration.minutes * 60,\n    } [defined(startsAt) && dateTime(endsAt) > dateTime(now())] | order(startsAt asc) [0...$sessionLimit],\n  },\n}': ActivitiesQueryResult;
    '*[_type == "infoPage" && slug.current == $slug][0]': InfoPageQueryResult;
    '\n  *[_type == "club" && slug.current == $slug][0] {\n    ...,\n    managers[] {\n      ...,\n      person->\n    }\n  }\n': ClubPageQueryResult;
    '*[_type == "siteSettings"][0]{ logo }': FaviconQueryResult;
    '{\n  "siteSettings": *[_type == "siteSettings"][0]{ footerText, contactEmail },\n  "infoPages": *[_type == "infoPage"] | order(order asc, title asc) {\n    title,\n    slug,\n    menuPlacement,\n  }\n}': FooterQueryResult;
    '{\n  "siteSettings": *[_type == "siteSettings"][0]{ logo },\n  "infoPages": *[_type == "infoPage"] | order(order asc, title asc) {\n    title,\n    slug,\n    menuPlacement,\n  },\n  "clubs": *[_type == "club"] | order(name asc) { name, slug }\n}': HeaderQueryResult;
    '*[_type == "location" && slug.current == $slug][0]{\n  ...,\n}': LokasjonQueryResult;
    '*[_type == "location"] | order(name asc)': LocationsQueryResult;
    '{\n  "settings": *[_type == "siteSettings"][0]{ heroTitle, heroText },\n  "intro": *[_type == "siteSettings"][0].intro,\n  "events": *[_type == "event" && endsAt > now()] | order(startsAt asc) {\n    ...,\n    location->,\n  }\n}': FrontPageQueryResult;
  }
}
